stages: # List of stages for jobs, and their order of execution
  - check
  - publish

check:
  image: node:22
  stage: check
  script:
    - yarn
    - yarn check

publish:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5
      alias: docker
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+/'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f
      Dockerfile --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache:latest
      --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/cache:latest,mode=max
      --tag $CI_REGISTRY_IMAGE:latest --tag
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag
      $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
